# Use base container to write your own container can use scratch container 
FROM ubuntu:14.04
MAINTAINER thimmarayan.krishnappa.gmail.com
RUN apt-get update -y && apt-get install apache2 -y 
CMD ["echo","helloworld"]


